ALTER TABLE TELEFONES_ALUNOS
ADD CONSTRAINT TELEFONE_ALUNO_FK
FOREIGN KEY (MATRICULA_ALUNO)
REFERENCES ALUNOS (MATRICULA_ALUNO);

ALTER TABLE ALUNOS_OFERTAS
ADD CONSTRAINT ALUNOS_ALUNO_FK
FOREIGN KEY (MATRICULA_ALUNO)
REFERENCES ALUNOS (MATRICULA_ALUNO);

ALTER TABLE ALUNOS_OFERTAS 
ADD CONSTRAINT ALUNOS_OFERTAS_FK
FOREIGN KEY (CODIGO_OFERTA)
REFERENCES OFERTAS (CODIGO_OFERTA);

ALTER TABLE OFERTAS
ADD CONSTRAINT OFERTAS_PROFESSOR_FK
FOREIGN KEY (MATRICULA_PROFESSOR)
REFERENCES PROFESSORES (MATRICULA_PROFESSOR);

ALTER TABLE OFERTAS
ADD CONSTRAINT OFERTAS_DISCIPLINAS_FK
FOREIGN KEY (CODIGO_DISCIPLINA)
REFERENCES DISCIPLINAS (CODIGO_DISCIPLINA);

ALTER TABLE DISCIPLINAS
ADD CONSTRAINT DISCIPLINAS_DEPENDENCIA_FK
FOREIGN KEY (CODIGO_DISCIPLINA_DEPENDENCIA)
REFERENCES DISCIPLINAS (CODIGO_DISCIPLINA)
