--SELECIONA TUDO DA TABELA ALUNOS
SELECT * FROM ALUNOS;


--SELECIONA TODOS OS ALUNOS QUE NASCERAM ATE 1/1/2000
SELECT MATRICULA_ALUNO 
, INITCAP(NOME_ALUNO) AS NOME_ALUNO
, TO_CHAR(DATA_NASCIMENTO, 'DD/MM/YYYY') AS
DATA_NASCIMENTO
FROM ALUNOS
WHERE DATA_NASCIMENTO <= TO_DATE('01/01/2000', 'DD/MM/YYYY');

--CONTA QUANTOS ALUNOS NASCERAM A PARTIR DE 1/1/2000
SELECT COUNT(1)
FROM ALUNOS
WHERE DATA_NASCIMENTO >= TO_DATE('01/01/2000', 'DD/MM/YYYY');

--SELECIONA A RELAÇÃO ENTRE A ALUNOS E TELEFONES
SELECT A.NOME_ALUNO
, T.TELEFONE
FROM ALUNOS A
INNER JOIN TELEFONES_ALUNOS T
ON A.MATRICULA_ALUNO = T.MATRICULA_ALUNO
ORDER BY A.NOME_ALUNO;

--SELECIONA TODOS QUE TEM ANTONIO NA COMPOSIÇÃO DO NOME
SELECT *
FROM ALUNOS
WHERE NOME_ALUNO LIKE '%ANTONIO%';

--VERIFICA NA TABELA DE OFERTAS 1=VERDADEIRO, TRAS TODOS OS PROFESSORES QUE NÃO POSSUEM OFERTAS
SELECT *
FROM PROFESSORES P
WHERE NOT EXISTS (SELECT 1
FROM OFERTAS O
WHERE O.MATRICULA_PROFESSOR =
P.MATRICULA_PROFESSOR);

--IN=COMPARADOR DE LISTA/ MOSTRA OS CODIGOS DAS DISCIPLINAS
SELECT *
FROM DISCIPLINAS
WHERE CODIGO_DISCIPLINA IN (85853, 75189);

--SELECIONA TODAS AS DISCIPLINAS QUE NÃO PRECISAM DE PRE-REQUISITO
SELECT *
FROM DISCIPLINAS
WHERE CODIGO_DISCIPLINA_DEPENDENCIA IS NULL;

--MOSTRA TUDO (GRADE HORARIA DOS ALUNOS)
SELECT A.NOME_ALUNO
, AO.SEMESTRE
, TO_CHAR(O.HORARIO_INICIAL, 'HH24:MI') AS HORARIO_INICIAL
, TO_CHAR(O.HORARIO_FINAL, 'HH24:MI') AS HORARIO_FINAL
, LOWER(O.DIA_SEMANA) AS DIA_SEMANA
, D.NOME_DISCIPLINA
, P.NOME_PROFESSOR
, D.CARGA_HORARIA
FROM ALUNOS_OFERTAS AO
INNER JOIN OFERTAS O
ON AO.CODIGO_OFERTA = O.CODIGO_OFERTA
INNER JOIN ALUNOS A
ON AO.MATRICULA_ALUNO = A.MATRICULA_ALUNO
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROFESSOR = P.MATRICULA_PROFESSOR
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA
WHERE D.CODIGO_DISCIPLINA_DEPENDENCIA IS NOT NULL
ORDER BY A.NOME_ALUNO;