ALTER TABLE TELEFONES ADD PRIMARY KEY (TELEFONE);

ALTER TABLE ALUNOS ADD PRIMARY KEY (MATRICULA_ALUNO);

ALTER TABLE ALUNOS_OFERTAS ADD PRIMARY KEY (MATRICULA_ALUNO);

ALTER TABLE ALUNOS_OFERTAS ADD PRIMARY KEY (CODIGO_OFERTA);

ALTER TABLE OFERTAS ADD PRIMARY KEY (CODIGO_OFERTA);

ALTER TABLE PROFESSORES ADD PRIMARY KEY (MATRICULA_PROFESSOR);

ALTER TABLE DISCIPLINAS ADD PRIMARY KEY (CODIGO_DISCIPLINA);