ALTER TABLE ALUNOS RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;

ALTER TABLE ALUNOS RENAME COLUMN NOME TO NOME_ALUNO;

ALTER TABLE PROFESSORES RENAME COLUMN MATRICULA TO MATRICULA_PROFESSOR;

ALTER TABLE PROFESSORES RENAME COLUMN NOME TO NOME_PROFESSOR;

ALTER TABLE DISCIPLINAS RENAME COLUMN EMENTA TO EMENTA_DISCIPLINA;

ALTER TABLE ALUNOS_OFERTAS RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;

ALTER TABLE OFERTAS RENAME COLUMN MATRICULA TO MATRICULA_PROFESSOR;

SELECT * FROM PROFESSORES;