CREATE INDEX ALUNOS_NOME_IDX ON ALUNOS
(NOME);

CREATE INDEX OFERTAS_DIA_IDX ON OFERTAS
(DIA_SEMANA);

CREATE INDEX DISCIPLINA_NOME_IDX ON DISCIPLINAS
(NOME_DISCIPLINA);

CREATE INDEX PROFESSORES_NOME_IDX ON PROFESSORES
(NOME);